### ISSUE TITLE
[Issue]: 竖屏模式下显示异常

### ISSUE THREAD

**Issue by aDropp** [Axixi2233/moonlight-android#3]
### Describe the bug

竖屏模式下显示异常
moonlight版本240819
sunshine版本v0.23.1
![PC设置](https://github.com/user-attachments/assets/895d2edc-7645-429f-bc2e-1c813e3c62ed)
![分辨率](https://github.com/user-attachments/assets/dcb3c093-e092-41f5-bd9d-0c3dd2e78792)
![显示画面](https://github.com/user-attachments/assets/1cfaf38f-173f-4f46-b72b-803aab03daf8)

### Steps to reproduce

无

### Affected games

无

### Other Moonlight clients

PC

### Moonlight adjusted settings

Yes

### Moonlight adjusted settings (please complete the following information)

视频分辨率设置为 本地（2560*1600）
启用 将画面拉伸至全屏
启用 填充刘海区域
启用 竖屏显示模式

### Moonlight default settings

No

### Gamepad-related connection issue

No

### Gamepad-related input issue

No

### Gamepad-related streaming issue

No

### Android version

Android 14

### Device model

Samsung Tab S7 FE

### Server PC OS version

Windows 11 23H2

### Server PC GeForce Experience version

No

### Server PC Nvidia GPU driver version

No

### Server PC antivirus and firewall software

火绒

**Comment by lak0769** [comment]
Moonlight新建分辨率1600x2560试试吧

**Comment by aDropp** [comment]
> Moonlight新建分辨率1600x2560试试吧

不行，同样的问题。中间那个是小写的英文字母x吗？

**Comment by lak0769** [comment]
是的，英文字母x，新增自定义分辨率之后需要退出设置页面，再次进入会出现一个本地的（1600x2560），同时勾选竖屏显示模式

**Comment by aDropp** [comment]
> 是的，英文字母x，新增自定义分辨率之后需要退出设置页面，再次进入会出现一个本地的（1600x2560），同时勾选竖屏显示模式

感谢，可以了。刚才新增自定义分辨率之后没有重新选分辨率。
